@baseurl = http://localhost:8002/
@token = HN#u{{,~x>m2FD7[
###
GET {{baseurl}}/test

###
GET {{baseurl}}/list-running-vms
content-type: application/json
Authorization: {{token}}

###
GET {{baseurl}}/usbs
content-type: application/json
Authorization: {{token}}

###
GET {{baseurl}}/disks
content-type: application/json
Authorization: {{token}}


###
GET {{baseurl}}/attach-disk/sdb/win10
content-type: application/json
Authorization: {{token}}

###
GET {{baseurl}}/attach-usb/13fe:4300/win11
content-type: application/json
Authorization: {{token}}

###
GET {{baseurl}}/detach-usb/13fe:4300/win11
content-type: application/json
Authorization: {{token}}

###
GET {{baseurl}}/attached-usbs/win11
content-type: application/json
Authorization: {{token}}



